import Link from "next/link";
import Head from "next/head";

export function NavbarLayout ({ children, title='Todos' }) {
    return (
<>
    <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={"logo.ico"} />
    </Head>
    <nav className={"navbar"}>
        <img  className={"logo"} src={'logo.svg'} alt='logo'/>
        <h1 >
            TODOS
        </h1>
        <div className={"wrapper"}>
            <Link href={"/"}><a> To home </a></Link>
            <Link href={"/newtodos"}><a> New todos </a></Link>
        </div>
    </nav>
    <main> {children} </main>
</>
    )
}